config/routes.rb
Rails.application.routes.draw do
  # Administrate
  namespace :admin do
    resources :users
    resources :products
    resources :orders
    resources :featured_products

    root to: "users#index"
  end

  # Clearance
  scope '/admin' do
    # resources :passwords, controller: "clearance/passwords", only: [:create, :new]
    resource :session, controller: "clearance/sessions", only: [:create]

    resources :users, controller: "clearance/users", only: [:create] do
      resource :password,
               controller: "clearance/passwords",
               only: [:edit, :update]
    end

    get "/sign_in" => "clearance/sessions#new", as: "sign_in"
    delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
    # get "/sign_up" => "clearance/users#new", as: "sign_up"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'products', to: 'products#index'
  get 'products/:id', to: 'products#show'
  get 'featured_products', to: 'products#featured'

  post 'users/sign_up', to: 'users#create'
  post 'users/login', to: 'sessions#create'
  delete 'users/logout', to: 'sessions#destroy'
  get 'users/is_logged_in', to: 'sessions#is_logged_in'

  resources :orders

  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this
# `Administrate::ApplicationController`, making it the ideal place to put
# authentication logic or other before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    include Clearance::Controller
    before_action :require_login

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

app/helpers/application_helper.rb
module ApplicationHelper
  def login!
    session[:user_id] = @user.id
  end

  def logout!
    session.clear
  end

  def logged_in?
    !!session[:user_id]
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  # Returns current user as a hash without :password_digest, :created_at and :updated_at
  def current_user_info
    current_user.attributes.except("password_digest", "created_at", "updated_at")
  end

  def authorized_user?
    @user == current_user
  end

  def set_user
    @user = User.find_by(id: session[:user_id])
  end
end

app/views/admin/application/_navigation.html.erb
<%#
# Navigation

This partial is used to display the navigation in Administrate.
By default, the navigation contains navigation links
for all resources in the admin dashboard,
as defined by the routes in the `admin/` namespace
%>

<% if signed_in? %>
	<nav class="navigation" role="navigation">
		<%= button_to 'Log out', sign_out_path, method: :delete, class: "button button--alt button--nav" %>

		<% Administrate::Namespace.new(namespace).resources_with_index_route.each do |resource| %>
			<%= link_to(
					display_resource_name(resource),
					resource_index_route(resource),
					class: "navigation__link navigation__link--#{nav_link_state(resource)}"
				) if accessible_action?(model_from_resource(resource), :index) %>
		<% end %>
	</nav>
<% end %>